---
- name: register dehydrated
  listen: dehydrated changed
  shell: "{{ dehydrated_install_dir }}/dehydrated --register --accept-terms"
  tags:
    - skip_ansible_lint

- name: generate certificate
  listen: dehydrated changed
  shell: "{{ dehydrated_install_dir }}/dehydrated -g -c -f {{ dehydrated_config_dir }}/config"
  tags:
    - skip_ansible_lint
